name 'gioppoluca-moodle'
version '0.0.1'

author 'Luca Gioppo'
license ''
project_page ''
source 'https://github.com/gioppoluca/puppet-moodle'
summary ''
description ''
dependency 'puppetlabs/apache', '>=0.4.0'
dependency 'puppetlabs/mysql', '>=0.5.0'
dependency 'puppetlabs/stdlib', '>=3.0.0'
