name 'gioppoluca-moodle'
version '0.0.1'

author 'Luca Gioppo'
license 'GPLv3'
project_page ''
source ''
summary ''
description ''
dependency 'puppetlabs/apache', '>=0.4.0'
dependency 'puppetlabs/mysql', '>=0.5.0'
dependency 'puppetlabs/stdlib', '>=3.0.0'
